{% set name = "sdtfile" %}
{% set version = "2024.12.6" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14478f9866f8546f82f1cdcbcfb9c24c7e7918befd960325b1921511b1f90f2d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - numpy >=1.22.0
    - python >={{ python_min }}

test:
  imports:
    - sdtfile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read Becker & Hickl SDT files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/sdtfile

extra:
  recipe-maintainers:
    - s-weigand
