{% set name = "sdtfile" %}
{% set version = "2024.5.24" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2aec1563a594fc4414442ab8b1409f2dcbb96d19198cb6ab2ed19301cc079dee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - numpy >=1.22.0
    - python >=3.9

test:
  imports:
    - sdtfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read Becker & Hickl SDT files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/sdtfile

extra:
  recipe-maintainers:
    - s-weigand
