{% set name = "sdtfile" %}
{% set version = "2023.8.30" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dbf5bfd8d4f501ac93901c90dfe4ae188fcdc01d7a357b0c10db19d92cb50a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - numpy >=1.19.2
    - python >=3.9

test:
  imports:
    - sdtfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read Becker & Hickl SDT files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/sdtfile

extra:
  recipe-maintainers:
    - s-weigand
