{% set name = "sdtfile" %}
{% set version = "2022.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c17cbbf386a88c98f186038c7118cbc82247e8166bb8115b30dcc3cda702a3b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.15.1
    - python >=3.7

test:
  imports:
    - sdtfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read Becker & Hickl SDT files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/sdtfile

extra:
  recipe-maintainers:
    - s-weigand
